#ifndef __RADIOM_DEFINES_H__
#define __RADIOM_DEFINES_H__

#ifndef RADIOM_FIFOBUF_CAPACITY
#define RADIOM_FIFOBUF_CAPACITY (32768)
#endif // RADIOM_FIFOBUF_CAPACITY

#define RADIOM_SUCCESS  (0)
#define RADIOM_ERROR    (-1)

#define RADIOM_RADIO_FREQUENCY (101700000)
#define RADIOM_RADIO_SAMPLE_RATE (2048000)

#define RADIOM_MAX_INT32 (0x7FFFFFFF)
#define RADIOM_MAX_INT64 (0x7FFFFFFFFFFFFFFF)

#endif // __RADIOM_DEFINES_H__